# Generated by Django 4.2.6 on 2023-11-21 08:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appLomal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamisasHombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('talla', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='images/hombre/camisasHombre/')),
            ],
        ),
        migrations.CreateModel(
            name='CamisasMujer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('talla', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='images/mujer/camisasMujer/')),
            ],
        ),
        migrations.CreateModel(
            name='SudaderasHombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('talla', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='images/hombre/sudaderasHombre/')),
            ],
        ),
        migrations.CreateModel(
            name='SudaderasMujer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('talla', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='images/mujer/sudaderasMujer/')),
            ],
        ),
        migrations.CreateModel(
            name='Tenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('talla', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='images/tenis/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('codigo', models.IntegerField()),
                ('talla', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('imagen', models.ImageField(upload_to='images/carrito/imagesCarrito/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLomal.usuarios')),
            ],
        ),
    ]
