# Generated by Django 4.2.6 on 2023-11-22 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLomal', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=100)),
                ('codigoProducto', models.IntegerField()),
                ('tallaProducto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('precioProducto', models.FloatField()),
                ('imagenProducto', models.ImageField(upload_to='images/productos/')),
                ('seccionProducto', models.CharField(max_length=100)),
                ('categoriaProducto', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CamisasHombre',
        ),
        migrations.DeleteModel(
            name='CamisasMujer',
        ),
        migrations.DeleteModel(
            name='SudaderasHombre',
        ),
        migrations.DeleteModel(
            name='SudaderasMujer',
        ),
        migrations.DeleteModel(
            name='Tenis',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='talla',
        ),
    ]
