# Generated by Django 4.2.6 on 2023-11-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLomal', '0003_productos_delete_camisashombre_delete_camisasmujer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigoProducto',
            field=models.IntegerField(unique=True),
        ),
    ]
