# Generated by Django 4.2.6 on 2023-11-23 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLomal', '0004_alter_productos_codigoproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camisas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=100)),
                ('codigoProducto', models.IntegerField(unique=True)),
                ('tallaProducto', models.IntegerField(choices=[('EXCH', 'EXCH'), ('CH', 'CH'), ('M', 'M'), ('G', 'G'), ('EXG', 'EXG')])),
                ('precioProducto', models.FloatField()),
                ('imagenProducto', models.ImageField(upload_to='images/productos/Camisas')),
                ('seccionProducto', models.CharField(choices=[('camisa', 'camisa'), ('pantalon', 'pantalon'), ('sudadera', 'sudadera'), ('teni', 'teni')], default='camisa', max_length=20)),
                ('categoriaProducto', models.CharField(choices=[('hombre', 'hombre'), ('mujer', 'mujer'), ('nino', 'nino')], default='hombre', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pantalones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=100)),
                ('codigoProducto', models.IntegerField(unique=True)),
                ('tallaProducto', models.IntegerField(choices=[('EXCH', 'EXCH'), ('CH', 'CH'), ('M', 'M'), ('G', 'G'), ('EXG', 'EXG')])),
                ('precioProducto', models.FloatField()),
                ('imagenProducto', models.ImageField(upload_to='images/productos/Pantalones')),
                ('seccionProducto', models.CharField(choices=[('camisa', 'camisa'), ('pantalon', 'pantalon'), ('sudadera', 'sudadera'), ('teni', 'teni')], default='camisa', max_length=20)),
                ('categoriaProducto', models.CharField(choices=[('hombre', 'hombre'), ('mujer', 'mujer'), ('nino', 'nino')], default='hombre', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sudaderas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=100)),
                ('codigoProducto', models.IntegerField(unique=True)),
                ('tallaProducto', models.IntegerField(choices=[('EXCH', 'EXCH'), ('CH', 'CH'), ('M', 'M'), ('G', 'G'), ('EXG', 'EXG')])),
                ('precioProducto', models.FloatField()),
                ('imagenProducto', models.ImageField(upload_to='images/productos/Sudaderas')),
                ('seccionProducto', models.CharField(choices=[('camisa', 'camisa'), ('pantalon', 'pantalon'), ('sudadera', 'sudadera'), ('teni', 'teni')], default='camisa', max_length=20)),
                ('categoriaProducto', models.CharField(choices=[('hombre', 'hombre'), ('mujer', 'mujer'), ('nino', 'nino')], default='hombre', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=100)),
                ('codigoProducto', models.IntegerField(unique=True)),
                ('tallaProducto', models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(20)])),
                ('precioProducto', models.FloatField()),
                ('imagenProducto', models.ImageField(upload_to='images/productos/Tenis')),
                ('seccionProducto', models.CharField(choices=[('camisa', 'camisa'), ('pantalon', 'pantalon'), ('sudadera', 'sudadera'), ('teni', 'teni')], default='camisa', max_length=20)),
                ('categoriaProducto', models.CharField(choices=[('hombre', 'hombre'), ('mujer', 'mujer'), ('nino', 'nino')], default='hombre', max_length=20)),
            ],
        ),
    ]
