# Generated by Django 4.2.6 on 2023-11-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLomal', '0005_camisas_pantalones_sudaderas_tenis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
