# Generated by Django 4.2.6 on 2023-11-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLomal', '0006_delete_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camisas',
            name='tallaProducto',
            field=models.CharField(choices=[('EXCH', 'EXCH'), ('CH', 'CH'), ('M', 'M'), ('G', 'G'), ('EXG', 'EXG')], max_length=4),
        ),
        migrations.AlterField(
            model_name='pantalones',
            name='tallaProducto',
            field=models.CharField(choices=[('EXCH', 'EXCH'), ('CH', 'CH'), ('M', 'M'), ('G', 'G'), ('EXG', 'EXG')], max_length=4),
        ),
        migrations.AlterField(
            model_name='sudaderas',
            name='tallaProducto',
            field=models.CharField(choices=[('EXCH', 'EXCH'), ('CH', 'CH'), ('M', 'M'), ('G', 'G'), ('EXG', 'EXG')], max_length=4),
        ),
    ]
