# Generated by Django 4.2.6 on 2023-11-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLomal', '0007_alter_camisas_tallaproducto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
